server:
  addr: ":8081"
  read_timeout: 60
  write_timeout: 60
  idle_timeout: 60
  domain: "localhost"

log:
  level: "info"

# Terraform registry configuration
terraform:
  registry_url: "https://registry.terraform.io"

# Cache configuration for external API proxying
cache:
  allowed_hosts:
    - github.com
    - api.github.com
    - gitlab.com
    - gitlab.example.com
    - registry.terraform.io
    - releases.hashicorp.com
    - checkpoint-api.hashicorp.com
  # Skip SSL certificate verification (use only for development or trusted hosts)
  skip_ssl_verify: false

# Storage backend configuration
storage:
  # Use S3/MinIO for distributed storage
  s3:
    enabled: true
    endpoint: "http://localhost:9000"
    region: "us-east-1"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    bucket: "proxy-cache"
    skip_ssl_verify: true

  # Alternative: Use local filesystem storage
  file:
    path: "/data/registry"

proxy:
  enabled: false
  type: "http"  # http, socks5, socks4
  host: "127.0.0.1"
  port: 8080
  username: ""
  password: ""
